### ISSUE TITLE
Asterisk 11/Asterisk13 and Clang-3.4+

### ISSUE THREAD

**Issue by dkgroot** [DragonFlyBSD/DeltaPorts#156]
I sent the asterisk group (digium) numerous patches to make it possible for asterisk11 and asterisk13 to be build using clang (which have all been merged a while back).

I am not sure if this is interesting information for FreeBSD / DragonFlyBSD. If you like i can do a couple of testruns using clang, to see what changes to the Makefile would be required.

Asterisk11 / Asterisk13 work perfectly fine using gcc, just asking if is the future preferred build tool?

**Comment by jrmarino** [comment]
I think gcc will be the ports compiler for the forseeable future.  We'd like to replace gcc44 base compiler with clang37 or higher and it would become an alternative but I'm not sure when it would take over from gcc for building ports.

and FreeBSD should be taking care of clang support since they don't have a choice.  If they force USE_GCC on it's because they have to.

**Comment by dkgroot** [comment]
Ok good to know. Thanks for the info.
